# Generated by Django 5.2.3 on 2025-09-10 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, choices=[(1000, '1000 INR (5 days)'), (2000, '2000 INR (10 days)'), (4000, '4000 INR (20 days)'), (6000, '6000 INR (30 days)')], null=True)),
                ('upi_last_four', models.CharField(blank=True, max_length=4)),
                ('admin_upi_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('enquiry', 'Enquiry'), ('pending', 'Pending Payment Verification'), ('active', 'Active'), ('completed', 'Completed')], default='enquiry', max_length=20)),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='campaigns.adrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
    ]
