# Generated by Django 5.2.5 on 2025-09-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_adrecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
