# Generated by Django 5.2.5 on 2025-09-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_adrecord_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
