# Generated by Django 5.2.5 on 2025-09-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_adrecord_requested_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adrecord',
            name='requested_duration_days',
        ),
    ]
