# Generated by Django 5.2.5 on 2025-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_adrecord_requested_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='hold_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='status',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('hold', 'On Hold'), ('pending', 'Pending Payment Verification'), ('active', 'Active'), ('completed', 'Completed')], default='enquiry', max_length=20),
        ),
    ]
