# Generated by Django 5.2.5 on 2025-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_adrecord_hold_reason_adrecord_hold_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='custom_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adrecord',
            name='custom_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adrecord',
            name='amount',
            field=models.IntegerField(blank=True, choices=[(1000, '1000 INR (5 days)'), (2000, '2000 INR (10 days)'), (4000, '4000 INR (20 days)'), (6000, '6000 INR (30 days)'), (0, 'Other (custom)')], null=True),
        ),
    ]
