# Generated by Django 5.2.3 on 2025-09-27 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_adrecord_custom_amount_adrecord_custom_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day1FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('contacted', models.BooleanField(default=False)),
                ('contact_method', models.CharField(blank=True, max_length=50)),
                ('response', models.TextField(blank=True)),
                ('ad_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day1_followup', to='campaigns.adrecord')),
            ],
            options={
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='Day2FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('contacted', models.BooleanField(default=False)),
                ('contact_method', models.CharField(blank=True, max_length=50)),
                ('response', models.TextField(blank=True)),
                ('ad_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day2_followup', to='campaigns.adrecord')),
            ],
            options={
                'ordering': ['-follow_up_date'],
            },
        ),
    ]
