# Generated by Django 5.2.5 on 2025-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day1followup',
            options={'ordering': ['follow_up_date']},
        ),
        migrations.AlterModelOptions(
            name='day2followup',
            options={'ordering': ['follow_up_date']},
        ),
        migrations.AlterField(
            model_name='day1followup',
            name='follow_up_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='day2followup',
            name='follow_up_date',
            field=models.DateField(),
        ),
    ]
