# Generated by Django 5.2.5 on 2025-09-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_alter_day1followup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrecord',
            name='follow_up_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
