# Generated by Django 5.2.5 on 2025-09-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_adrecord_follow_up_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adrecord',
            name='follow_up_completed',
        ),
    ]
